// Lista de palabras falsas en la base de datos
const wordDatabase = [
    {tema: "Animal", palabra: "lleo"},
    {tema: "Animal", palabra: "moix"},
    {tema: "Animal", palabra: "cavall"},
    {tema: "Animal", palabra: "zebra"},
    {tema: "Animal", palabra: "pingui"},
    {tema: "Animal", palabra: "ferreret"},
    {tema: "Animal", palabra: "voltor"},
    {tema: "Animal", palabra: "elefant"},
    {tema: "Animal", palabra: "aranya"},
    {tema: "Animal", palabra: "peix"},
    {tema: "Animal", palabra: "jirafa"},
    {tema: "Animal", palabra: "cabra"},
    {tema: "Animal", palabra: "serp"},
    {tema: "Animal", palabra: "delfi"},
    {tema: "Animal", palabra: "ovella"},
    {tema: "Fruita", palabra: "poma"},
    {tema: "Fruita", palabra: "pera"},
    {tema: "Fruita", palabra: "kiwi"},
    {tema: "Fruita", palabra: "sindria"},
    {tema: "Fruita", palabra: "plata"},
    {tema: "Fruita", palabra: "taronja"},
    {tema: "Fruita", palabra: "llimona"},
    {tema: "Fruita", palabra: "pressec"},
    {tema: "Fruita", palabra: "pinya"},
    {tema: "Fruita", palabra: "vermell"},
    {tema: "Color", palabra: "groc"},
    {tema: "Color", palabra: "verd"},
    {tema: "Color", palabra: "blau"},
    {tema: "Color", palabra: "lila"},
    {tema: "Color", palabra: "rosa"},
    {tema: "Color", palabra: "marro"},
    {tema: "Color", palabra: "negre"},
    {tema: "Color", palabra: "blanc"},
    {tema: "Instrument musical", palabra: "piano"},
    {tema: "Instrument musical", palabra: "guitarra"},
    {tema: "Instrument musical", palabra: "flauta"},
    {tema: "Instrument musical", palabra: "violí"},
    {tema: "Instrument musical", palabra: "tambor"},
    {tema: "Instrument musical", palabra: "harmonica"},
    {tema: "Menjar", palabra: "pastis"},
    {tema: "Menjar", palabra: "gelat"},
    {tema: "Menjar", palabra: "arros"},
    {tema: "Menjar", palabra: "pizza"},
    {tema: "Menjar", palabra: "truita"},
    {tema: "Menjar", palabra: "sobrassada"},
    {tema: "Esports", palabra: "futbol"},
    {tema: "Esports", palabra: "basquet"},
    {tema: "Esports", palabra: "tennis"},
    {tema: "Esports", palabra: "volei"},
    {tema: "Esports", palabra: "hoquei"},
]
// alert(wordDatabase.length)